project:
  type: website
  output-dir: docs

website:
  title: "Breast Cancer Symptom Explorer"
  repo-url: https://github.com/cshsbiostats/breast-cancer-symptom-explorer
  repo-actions: [edit, issue]
  repo-branch: master
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Research Facing Tools
        menu: 
          - b35-bcse-combined.qmd
      - text: Patient Facing Tools
        menu: 
          - b35-patient-facing-explorer.qmd
      - href: contact.qmd
        text: Contact
    tools:
    - icon: github
      href: https://github.com/cshsbiostats
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

